### ISSUE TITLE
Question about tag of To-Read

### ISSUE THREAD

**Issue by kuangxiaoye** [NicoleMayer/zotero-save-with-tag#1]
Hi ,Im using your tool,it very nice. but I have a question.

when new artical was added,I just need tag on the title of artical .But It is not necessary that the pdf was added tag also.

**Comment by kuangxiaoye** [comment]
supplement： MacOS

**Comment by hxsnow10** [comment]
+1， attchments is wished without tag， for tag searching will include attchments

**Comment by ghost** [comment]
+1

**Comment by kuangxiaoye** [comment]
兄弟们 问题解决了  直接下 Zotero-If 插件就好了 

也有添加tag功能 不会添加附件

Issue提了这么久这老外也不理人 看来他自己也不用 笑死

问题关了 链接在下面
 
https://github.com/qnscholar/zotero-if

**Comment by NicoleMayer** [comment]
首先祝贺你找到了解决方法，我前段时间在外面玩一直没看邮件不知道情况，并不存在主观上不理人。
这个工具是我当时自己有这个需求，但没有搜到现成的解决方法，随便写的代码并不完善，现在也不用了所以没有维护的打算。
你们有需要的话可以使用更成熟的工具 https://github.com/windingwind/zotero-tag。
